In [3]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/archivos/3.1.csv",
    encoding="cp1252",
    header=None
)

In [4]:
df.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Tabla N°:,3.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Nombre de la tabla:,Viviendas particulares ocupadas por tipo de se...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Fuente:,VIII Censo de Población y VII de Vivienda,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,Elaboración:,Instituto Nacional de Estadística y Censos (IN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Índice,"Provincia, cantón y área",NaN,NaN,Número total de viviendas particulares ocupadas,Tipo de servicio higiénico en la vivienda,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,"Inodoro o escusado, conectado a red pública de...","Inodoro o escusado, conectado a pozo séptico","Inodoro o escusado, conectado a biodigestor","Inodoro o escusado, conectado a pozo ciego","Inodoro o escusado, con descarga directa al ma...",Letrina,No tiene
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Total Nacional,Nacional,Nacional,"5,062,650","3,330,851","1,222,743","10,019","213,824","48,483","59,285","177,445"
12,NaN,Total Nacional,Nacional,Urbana,"3,238,614","2,677,671","456,526","4,072","43,999","19,149","6,526","30,671"
13,NaN,Total Nacional,Nacional,Rural,"1,824,036","653,180","766,217","5,947","169,825","29,334","52,759","146,774"
14,NaN,Azuay,Total Azuay,Total Azuay,"242,168","174,655","52,616","1,212","3,058","3,036",527,"7,064"

In [5]:
pd.set_option("display.max_columns", None)

df.iloc[5:25]

,0,1,2,3,4,5,6,7,8,9,10,11
5,NaN,Elaboración:,Instituto Nacional de Estadística y Censos (IN...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Índice,"Provincia, cantón y área",NaN,NaN,Número total de viviendas particulares ocupadas,Tipo de servicio higiénico en la vivienda,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,"Inodoro o escusado, conectado a red pública de...","Inodoro o escusado, conectado a pozo séptico","Inodoro o escusado, conectado a biodigestor","Inodoro o escusado, conectado a pozo ciego","Inodoro o escusado, con descarga directa al ma...",Letrina,No tiene
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Total Nacional,Nacional,Nacional,"5,062,650","3,330,851","1,222,743","10,019","213,824","48,483","59,285","177,445"
12,NaN,Total Nacional,Nacional,Urbana,"3,238,614","2,677,671","456,526","4,072","43,999","19,149","6,526","30,671"
13,NaN,Total Nacional,Nacional,Rural,"1,824,036","653,180","766,217","5,947","169,825","29,334","52,759","146,774"
14,NaN,Azuay,Total Azuay,Total Azuay,"242,168","174,655","52,616","1,212","3,058","3,036",527,"7,064"
15,NaN,Azuay,Total Azuay,Urbana,"131,740","127,343","2,976",227,207,657,26,304
16,NaN,Azuay,Total Azuay,Rural,"110,428","47,312","49,640",985,"2,851","2,379",501,"6,760"
17,NaN,Azuay,Cuenca,Total Cuenca,"180,009","146,907","25,500",772,877,"2,441",209,"3,303"
18,NaN,Azuay,Cuenca,Urbana,"113,949","111,248","1,641",184,93,562,17,204
19,NaN,Azuay,Cuenca,Rural,"66,060","35,659","23,859",588,784,"1,879",192,"3,099"
20,NaN,Azuay,Girón,Total Girón,"3,758","1,742","1,715",44,80,29,15,133
21,NaN,Azuay,Girón,Urbana,"1,293","1,239",39,1,2,9,1,2
22,NaN,Azuay,Girón,Rural,"2,465",503,"1,676",43,78,20,14,131
23,NaN,Azuay,Gualaceo,Total Gualaceo,"12,435","4,665","5,524",53,984,118,44,"1,047"
24,NaN,Azuay,Gualaceo,Urbana,"4,101","3,639",389,11,26,20,1,15

In [6]:
df_datos = df.iloc[11:].copy()

df_datos.head(10)

,0,1,2,3,4,5,6,7,8,9,10,11
11,NaN,Total Nacional,Nacional,Nacional,"5,062,650","3,330,851","1,222,743","10,019","213,824","48,483","59,285","177,445"
12,NaN,Total Nacional,Nacional,Urbana,"3,238,614","2,677,671","456,526","4,072","43,999","19,149","6,526","30,671"
13,NaN,Total Nacional,Nacional,Rural,"1,824,036","653,180","766,217","5,947","169,825","29,334","52,759","146,774"
14,NaN,Azuay,Total Azuay,Total Azuay,"242,168","174,655","52,616","1,212","3,058","3,036",527,"7,064"
15,NaN,Azuay,Total Azuay,Urbana,"131,740","127,343","2,976",227,207,657,26,304
16,NaN,Azuay,Total Azuay,Rural,"110,428","47,312","49,640",985,"2,851","2,379",501,"6,760"
17,NaN,Azuay,Cuenca,Total Cuenca,"180,009","146,907","25,500",772,877,"2,441",209,"3,303"
18,NaN,Azuay,Cuenca,Urbana,"113,949","111,248","1,641",184,93,562,17,204
19,NaN,Azuay,Cuenca,Rural,"66,060","35,659","23,859",588,784,"1,879",192,"3,099"
20,NaN,Azuay,Girón,Total Girón,"3,758","1,742","1,715",44,80,29,15,133

In [9]:
df_el_oro = df_datos[df_datos[1] == "El Oro"]
df_el_oro.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11
188,NaN,El Oro,Total El Oro,Total El Oro,"216,642","170,804","30,367",372,"3,075","7,097",537,"4,390"
189,NaN,El Oro,Total El Oro,Urbana,"170,478","151,238","12,028",173,"1,231","3,272",287,"2,249"
190,NaN,El Oro,Total El Oro,Rural,"46,164","19,566","18,339",199,"1,844","3,825",250,"2,141"
191,NaN,El Oro,Machala,Total Machala,"92,040","80,275","7,524",97,859,"2,016",235,"1,034"
192,NaN,El Oro,Machala,Urbana,"86,605","78,807","4,922",93,548,"1,218",169,848
193,NaN,El Oro,Machala,Rural,"5,435","1,468","2,602",4,311,798,66,186
194,NaN,El Oro,Arenillas,Total Arenillas,"9,949","6,986","2,290",8,176,155,24,310
195,NaN,El Oro,Arenillas,Urbana,"6,592","5,712",649,5,50,47,7,122
196,NaN,El Oro,Arenillas,Rural,"3,357","1,274","1,641",3,126,108,17,188
197,NaN,El Oro,Atahualpa,Total Atahualpa,"1,958","1,106",445,10,94,277,1,25
198,NaN,El Oro,Atahualpa,Urbana,564,544,7,2,7,4,NaN,NaN
199,NaN,El Oro,Atahualpa,Rural,"1,394",562,438,8,87,273,1,25
200,NaN,El Oro,Balsas,Total Balsas,"2,394","1,292",251,2,30,763,7,49
201,NaN,El Oro,Balsas,Urbana,"1,399",948,18,NaN,7,389,1,36
202,NaN,El Oro,Balsas,Rural,995,344,233,2,23,374,6,13

In [11]:
df_cantones = df_el_oro[
    (df_el_oro[3].str.startswith("Total")) &
    (df_el_oro[2] != "Total El Oro")
]
df_cantones.head(15)

,0,1,2,3,4,5,6,7,8,9,10,11
191,NaN,El Oro,Machala,Total Machala,"92,040","80,275","7,524",97,859,"2,016",235,"1,034"
194,NaN,El Oro,Arenillas,Total Arenillas,"9,949","6,986","2,290",8,176,155,24,310
197,NaN,El Oro,Atahualpa,Total Atahualpa,"1,958","1,106",445,10,94,277,1,25
200,NaN,El Oro,Balsas,Total Balsas,"2,394","1,292",251,2,30,763,7,49
203,NaN,El Oro,Chilla,Total Chilla,772,366,265,1,62,6,5,67
206,NaN,El Oro,El Guabo,Total El Guabo,"17,090","11,459","4,543",62,242,212,37,535
209,NaN,El Oro,Huaquillas,Total Huaquillas,"16,936","12,704","3,249",11,207,68,49,648
212,NaN,El Oro,Marcabelí,Total Marcabelí,"2,095","1,652",291,NaN,24,96,4,28
215,NaN,El Oro,Pasaje,Total Pasaje,"25,860","20,849","3,656",26,207,632,66,424
218,NaN,El Oro,Piñas,Total Piñas,"9,378","6,142","1,440",19,331,"1,346",21,79
221,NaN,El Oro,Portovelo,Total Portovelo,"4,287","3,323",704,5,107,83,9,56
224,NaN,El Oro,Santa Rosa,Total Santa Rosa,"24,310","18,806","3,476",98,468,819,36,607
227,NaN,El Oro,Zaruma,Total Zaruma,"7,759","4,792","1,677",30,238,564,23,435
230,NaN,El Oro,Las Lajas,Total Las Lajas,"1,814","1,052",556,3,30,60,20,93

In [13]:
print("Número de cantones:", len(df_cantones))

df_cantones[[2, 3, 4, 5]]

Número de cantones: 14

              2                 3       4       5
191     Machala     Total Machala  92,040  80,275
194   Arenillas   Total Arenillas   9,949   6,986
197   Atahualpa   Total Atahualpa   1,958   1,106
200      Balsas      Total Balsas   2,394   1,292
203      Chilla      Total Chilla     772     366
206    El Guabo    Total El Guabo  17,090  11,459
209  Huaquillas  Total Huaquillas  16,936  12,704
212   Marcabelí   Total Marcabelí   2,095   1,652
215      Pasaje      Total Pasaje  25,860  20,849
218       Piñas       Total Piñas   9,378   6,142
221   Portovelo   Total Portovelo   4,287   3,323
224  Santa Rosa  Total Santa Rosa  24,310  18,806
227      Zaruma      Total Zaruma   7,759   4,792
230   Las Lajas   Total Las Lajas   1,814   1,052

vamos a calcular el porcentaje de viviendas conectadas a la red pública de alcantarillado.

In [18]:
df_cantones.dtypes

0     str
1     str
2     str
3     str
4     str
5     str
6     str
7     str
8     str
9     str
10    str
11    str
dtype: object

In [19]:
df_cantones[4] = pd.to_numeric(
    df_cantones[4].str.replace(",", "", regex=False),
    errors="raise"
)

In [20]:
df_cantones[[4, 5]].dtypes

4    int64
5      str
dtype: object

In [21]:
df_cantones[5] = pd.to_numeric(
    df_cantones[5].str.replace(",", "", regex=False),
    errors="raise"
)

In [22]:
df_cantones[[4, 5]].dtypes

4    int64
5    int64
dtype: object

In [27]:
# Indicador: Porcentaje de viviendas particulares ocupadas
# conectadas a la red pública de alcantarillado.
# Fuente: INEC, Censo de Población y Vivienda 2022.
# Unidad de análisis: vivienda particular ocupada.
# Desagregación: cantón.

df_cantones["cobertura_pct"] = (df_cantones[5] / df_cantones[4]) * 100

#redondear
df_cantones["cobertura_pct"] = df_cantones["cobertura_pct"].round(2)

#nombre de las columnas
df_cantones = df_cantones.rename(columns={
    2: "canton",
    4: "total_viviendas",
    5: "viviendas_alcantarillado"
})

In [29]:
df_cantones[
    ["canton", "total_viviendas",
     "viviendas_alcantarillado", "cobertura_pct"]
]

         canton  total_viviendas  viviendas_alcantarillado  cobertura_pct
191     Machala            92040                     80275          87.22
194   Arenillas             9949                      6986          70.22
197   Atahualpa             1958                      1106          56.49
200      Balsas             2394                      1292          53.97
203      Chilla              772                       366          47.41
206    El Guabo            17090                     11459          67.05
209  Huaquillas            16936                     12704          75.01
212   Marcabelí             2095                      1652          78.85
215      Pasaje            25860                     20849          80.62
218       Piñas             9378                      6142          65.49
221   Portovelo             4287                      3323          77.51
224  Santa Rosa            24310                     18806          77.36
227      Zaruma             7759                      4792          61.76
230   Las Lajas             1814                      1052          57.99

In [30]:
#canton con menor cobertura de alcantarillado
df_cantones[df_cantones["cobertura_pct"] == df_cantones["cobertura_pct"].min()]

,0,1,canton,3,total_viviendas,viviendas_alcantarillado,6,7,8,9,10,11,cobertura_pct
203,NaN,El Oro,Chilla,Total Chilla,772,366,265,1,62,6,5,67,47.41

In [31]:
#cantones ordenados de menor a mayor cobertura de alcantarillado
df_cantones.sort_values(by="cobertura_pct", ascending=True)

,0,1,canton,3,total_viviendas,viviendas_alcantarillado,6,7,8,9,10,11,cobertura_pct
203,NaN,El Oro,Chilla,Total Chilla,772,366,265,1,62,6,5,67,47.41
200,NaN,El Oro,Balsas,Total Balsas,2394,1292,251,2,30,763,7,49,53.97
197,NaN,El Oro,Atahualpa,Total Atahualpa,1958,1106,445,10,94,277,1,25,56.49
230,NaN,El Oro,Las Lajas,Total Las Lajas,1814,1052,556,3,30,60,20,93,57.99
227,NaN,El Oro,Zaruma,Total Zaruma,7759,4792,"1,677",30,238,564,23,435,61.76
218,NaN,El Oro,Piñas,Total Piñas,9378,6142,"1,440",19,331,"1,346",21,79,65.49
206,NaN,El Oro,El Guabo,Total El Guabo,17090,11459,"4,543",62,242,212,37,535,67.05
194,NaN,El Oro,Arenillas,Total Arenillas,9949,6986,"2,290",8,176,155,24,310,70.22
209,NaN,El Oro,Huaquillas,Total Huaquillas,16936,12704,"3,249",11,207,68,49,648,75.01
224,NaN,El Oro,Santa Rosa,Total Santa Rosa,24310,18806,"3,476",98,468,819,36,607,77.36
221,NaN,El Oro,Portovelo,Total Portovelo,4287,3323,704,5,107,83,9,56,77.51
212,NaN,El Oro,Marcabelí,Total Marcabelí,2095,1652,291,NaN,24,96,4,28,78.85
215,NaN,El Oro,Pasaje,Total Pasaje,25860,20849,"3,656",26,207,632,66,424,80.62
191,NaN,El Oro,Machala,Total Machala,92040,80275,"7,524",97,859,"2,016",235,"1,034",87.22